name: "Weekly changelog update"

on:
  schedule:
    - cron: "45 0 * * 1"

jobs:
  weekly-changelog:
    # if: github.repository == 'CleverRaven/Cataclysm-DDA'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Get current date"
        uses: 1466587594/get-current-time@v2
        id: current-date
        with:
          format: 'YYYYMMDD'
      - name: "Get changes since last week"
        id: getting-changes
        env:
          CURR_DATE: ${{ steps.current-date.outputs.formattedTime }}
        run: |
          tools/generate_changelog.py -f --by-date /tmp/changelog.txt -T "${{ secrets.TX_TOKEN }}" "$(date -d "@$(( $(date +%s -d $CURR_DATE) - (60*60*24*7) ))" +"%Y-%m-%d")"
          tac /tmp/changelog.txt > /tmp/changelog_rev.txt
          tools/merge_summaries.sh /tmp/changelog_rev.txt data/changelog.txt
          echo "::set-output name=date::$( date +"%Y-%m-%d" -d $CURR_DATE )"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Weekly Changelog ${{ steps.getting-changes.outputs.date }}
          committer: David Seguin <davidseguin@live.ca>
          author: David Seguin <davidseguin@live.ca>
          token: ${{ secrets.TX_PR_CREATOR }}
          branch: changelog-weekly
          delete-branch: true
          base: master
          title: Weekly Changelog ${{ steps.getting-changes.outputs.date }}
          body: "#### Summary\nNone\n"
          labels: Organization,<Documentation>
          # create as a draft to allow maintainers to cull the changes before merging
          draft: true
